export const PRICE_PLAN = [
  {
    title: "Starter",
    description: "Perfect for trying out",
    price: "Free",
    duration: "",
    features: ["1 Subdomain", "2 Team memebrs", "Unlimited pipeline"],
    priceId: "",
  },
  {
    title: "Pro",
    description: "The ultimate agency kit",
    price: "19",
    duration: "month",
    features: [
      "5 Subdomain",
      "5 Team memebrs",
      "Unlimited pipeline",
      "Advanced analytics dashboard",
      "Customizable reports and charts",
      "Real-time data tracking",
    ],
    priceId: "price_ferejferherljreh",
    featured: true,
  },
  {
    title: "Premium",
    description: "Perfect for serious agency",
    price: "120",
    duration: "month",
    features: [
      "Unlimited Subdomain",
      "10 Team memebrs",
      "Unlimited pipeline",
      "Unlimited data storage",
      "Advanced data segmentation",
    ],
    priceId: "price_ferhelrhelrorehrf",
  },
];
